media:
  input: src/assets/media
  output: /src/assets/media
content:
  - name: articles
    label: Articles
    type: collection
    path: src/content/articles
    filename: "{primary}.md"
    primary: title
    view:
      fields: [title, pubDate]
      sort: [ pubDate, title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: slug, label: Slug, type: string, hidden: true }
      - { name: pubDate, label: Date, type: date, required: true }
      - { name: author, label: Author, type: string, required: true }
      - { name: cover, label: Cover, type: image, required: true }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text, required: true }
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    filename: "{primary}.json"
    primary: name
    view:
      fields: [name]
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: link, label: Link, type: string, required: true }
  - name: about
    label: About Page
    type: file
    path: src/pages/about/index.md
    fields:
      - {
          name: layout,
          type: string,
          hidden: true,
          default: "../../layouts/AboutLayout.astro",
        }
      - { name: title, label: Title, type: string, required: true }
      - { name: subtitle, label: Subtitle, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: author, label: Author, type: string, required: true }
      - { name: cover, label: Cover, type: image, required: true }
      - { name: body, label: Body, type: rich-text }
